# Generated by Django 5.0.1 on 2024-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=32, null=True, verbose_name='Сессионный ключ'),
        ),
    ]
